language: python
python: '3.8'
jobs:
  include:
    - name: 'Pylint'
      install:
        - pip install .
        - pip install pylint pylint-quotes
      script:
        - pylint confugue
    - name: 'Mypy'
      install:
        - pip install .
        - pip install mypy
      script:
        - mypy confugue
    - name: 'Unit tests (Python 3.5)'
      python: '3.5'
      install:
        - pip install .
        - pip install pytest
      script:
        - pytest tests -rp --log-cli-level=DEBUG
    - name: 'Unit tests (Python 3.8)'
      install:
        - pip install .
        - pip install pytest
      script:
        - pytest tests -rp --log-cli-level=DEBUG
    - name: 'Code style'
      install:
        - pip install pycodestyle pydocstyle
      script:
        - pycodestyle confugue
        - pydocstyle confugue
